name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build and test 99problems
        uses: ./.github/actions/build_and_test
        with:
          project: 99problems
      - name: Build and test DataStructures
        uses: ./.github/actions/build_and_test
        with:
          project: DataStructures
